### ISSUE TITLE
[Datahub] Organization Page

### ISSUE THREAD

**Issue by IGNF-Xavier** [geonetwork/geonetwork-ui#772]
In the section Organization, click on the organization will display the page of the organization with different tabs: 
- Description of the organization
- Datasets of the organization
- Re-use of datasets of the organization
- Information : Statistics and members
- Eventually others tabs if other things are stored and tagged with this organization in the geonetwork catalog/

(maybe to realize it, it needs to define a scheme for the metadata of an organization)

**Comment by jahow** [comment]
@IGNF-Xavier After looking into this request a bit more I have a few questions:
* members list cannot be shown as most of the time the user will not have the rights to access it (this is typically reserved to authenticated users with certain rights in GeoNetwork)
* the concept of "reuse" does not exist yet in GeoNetwork-UI so, until this concept is implemented, this information cannot be shown as well

Taking this into account, it feels like this page would be quite empty. In the current model used in GeoNetwork-UI, organizations really don't hold that much information apart from a logo and a name/description. Having a list of datasets for an org is already what happens when someone clicks on it, since it triggers a search with the associated filter.

On the other hand, the metadata-editor application offers a rudimentary dashboard for authenticated users, and that includes showing a list of records and members for an organization. I feel like this would be a batter place to expand on these functionalities, what do you think?

**Comment by IGNF-Xavier** [comment]
@jahow 

**List Member**
For the list member, can the datahub be connected to another IAM ? If it is the case, the list members could be authorized (in a certain limit) to be shown.

**Reuse medatata**
ISO19115 also remains used for reuse metadata.
Here is a first example of reuse metadata: https://catalogue.sigloire.fr/geonetwork/srv/api/records/95ff6a8c-1727-4eef-a88d-b104934e608e/formatters/xml
The use of the keyword _Reutilisation_ or _Reuse_ in the XML of the metadata could provoke a different behavior in the datahub to show list and pages of Reuse. 

**Organization**
We can use the same trick as Reuse metadata and also for another item we could reference (storymaps, etc)

**Comment by jahow** [comment]
> **List Member** For the list member, can the datahub be connected to another IAM ? If it is the case, the list members could be authorized (in a certain limit) to be shown.

GeoNetwork can be integrated with various authentication providers, but the users list will always be restricted to authenticated users. Since we're only relying on this backend, I don't see much opportunity for showing a list of users. And to be honest it would feel strange to show a list of users publicly, wouldn't that be a violation of GDPR?

> **Reuse medatata** ISO19115 also remains used for reuse metadata. Here is a first example of reuse metadata: https://catalogue.sigloire.fr/geonetwork/srv/api/records/95ff6a8c-1727-4eef-a88d-b104934e608e/formatters/xml The use of the keyword _Reutilisation_ or _Reuse_ in the XML of the metadata could provoke a different behavior in the datahub to show list and pages of Reuse.

Indeed, reuses could be documented as metadata as well, that makes sense. A simple keyword might not be enough to differentiate it in a reliable way; I looked at possible values for the ISO hierarchy level field but couldn't find anything matching well.

> **Organization** We can use the same trick as Reuse metadata and also for another item we could reference (storymaps, etc)

I'm not sure I understand, do you envision documenting Organizations through metadata as well?

**Comment by IGNF-Xavier** [comment]
**Organization**
`I'm not sure I understand, do you envision documenting Organizations through metadata as well?`
Yes
**Reuses**
For reuses, in the example, it is the  keyword _infoMapAccessService_ whic allow the identification as a reuse but it is specific for this example and don't include all types of reuses.
**Users**
Not if it is only their surname. It is not a priority

**Comment by IGNF-Xavier** [comment]
The Team Norma at IGN suggest to use nonGeographicDataset in MD_ScopeCode CodeList
If we are in the case where a dataset is used for another dataset, it will be also a dataset and eventually can be described in another metadata as a reuse

**Comment by jahow** [comment]
I'm not sure that `nonGeographicDataset` conveys the right meaning? Also, a reuse of a dataset could be either an application, a software, a product, a service... All these are scope codes as well.

Maybe using an association type code of `dependency` could be more relevant?

**Comment by IGNF-Xavier** [comment]
For an **Inspire** Discovery Service, it is ISO19115-1 which is used and dependency is not available in this version

Our options seem to be in this list
![image](https://github.com/geonetwork/geonetwork-ui/assets/98382923/1cf3469b-46eb-4f80-80d3-fac7e9b7b5b8)


The keyword had the advantage to allow us to choose the term to apply. We only need to implement it in the workflow of the edition of a reuse metadata
